# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- bash: |
    docker pull mongo:latest
  displayName: Pull Docker image

- task: Docker@2
  inputs:
    containerRegistry: 'RJ Aqua Reg'
    command: 'login'

- bash: |
    docker pull registry.aquasec.com/scanner6.5
  displayName: Login Aqua Reg

- task: aquasecScanner@4
  inputs:
    image: 'mongo:latest'
    scanType: 'local'
    register: false
    registry: false
    hideBase: false
    showNegligible: true
    scanner: 'registry.aquasec.com/scanner:6.5'
    connection: 'RJ Aqua Demo Env'
    customFlags: '--layer-vulnerabilities'